'use client'

import { useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Film, Languages, Menu, Play, Star, X } from 'lucide-react'
import { useLocale } from '@/components/locale-provider'
import { FeaturedAlbums } from '@/components/featured-albums'
import { MinimalYouTubePlayer } from '@/components/minimal-youtube-player'

const testimonials = [
  {
    name: 'Lyndsey DeRamus',
    role: 'Bride & creative collaborator',
    quote: 'The video is absolutely stunning — the quality is phenomenal. You curated something so intimate and beautiful from such a brief interaction.',
  },
  {
    name: 'Ana',
    role: 'Wedding filmmaker',
    quote: 'It looks like something made for a commercial. The colors have a beautiful cinematic, vintage feel, and the film made us genuinely emotional.',
  },
]

const packages = [
  {
    name: 'Half Day',
    price: '€1,200',
    note: 'Four cinematic hours for the moments that matter most.',
    features: ['4 hours of videography', 'One location only', '~90-second highlight film', '~15-second teaser', 'Ceremony and vows clip', 'Videos delivered in 4K resolution', 'Planning guidance & location scouting', 'Private online film delivery', 'Teaser delivered within 1 week', 'Full films delivered within 4 weeks'],
  },
  {
    name: 'Full Day',
    price: '€2,000',
    note: 'Eight hours to let your whole Italian story unfold.',
    features: ['8 hours of videography', 'Two locations included', '~3-minute highlight film', '~20-second teaser', 'Uncut full vows clip', 'Videos delivered in 4K resolution', 'Drone footage included when weather and local regulations allow', 'Dynamic, modern editing style', 'Music selection & licensing', 'Sound design', 'Travel fees included', 'Video delivery via download link'],
    featured: true,
  },
]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const { isItalian, toggleLocale } = useLocale()
  const [submitted, setSubmitted] = useState(false)

  return (
    <main className="min-h-screen bg-ivory text-ink">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/20 bg-ink/35 text-white backdrop-blur-md">
        <div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12">
          <a href="#top" className="flex w-[148px] items-center sm:w-[178px]" aria-label="Anvance Elopement home"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/anvanceelopmentlogo-aXDhassIf5mIXnPRdFpEdZ8EBnS1az.png" alt="Anvance Elopement" className="h-auto w-full object-contain" /></a>
          <nav className="hidden items-center gap-9 text-[11px] uppercase tracking-[0.22em] md:flex" aria-label="Main navigation">
            <a href="#story" className="transition-opacity hover:opacity-60">Our approach</a>
            <a href="/portfolio" className="transition-opacity hover:opacity-60">Portfolio</a>
            <a href="#places" className="transition-opacity hover:opacity-60">Italy</a>
            <a href="#investment" className="transition-opacity hover:opacity-60">Investment</a>
            <a href="/about" className="transition-opacity hover:opacity-60">{isItalian ? 'Chi siamo' : 'About'}</a><a href="/contact" className="border-b border-white pb-1 transition-opacity hover:opacity-60">{isItalian ? 'Contatti' : 'Contact'}</a><button type="button" onClick={toggleLocale} className="inline-flex items-center gap-2 border-l border-white/30 pl-5 text-[10px] tracking-[.18em]" aria-label="Switch language"><Languages size={14} />{isItalian ? 'EN' : 'IT'}</button>
          </nav>
          <button className="md:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button>
        </div>
        {menuOpen && <nav className="flex flex-col gap-5 border-t border-white/20 bg-ink px-6 py-7 text-sm uppercase tracking-[0.2em] md:hidden" aria-label="Mobile navigation"><a href="#story" onClick={() => setMenuOpen(false)}>Our approach</a><a href="/portfolio" onClick={() => setMenuOpen(false)}>Portfolio</a><a href="#places" onClick={() => setMenuOpen(false)}>Italy</a><a href="#investment" onClick={() => setMenuOpen(false)}>Investment</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><a href="/about" onClick={() => setMenuOpen(false)}>{isItalian ? 'Chi siamo' : 'About'}</a><a href="/contact" onClick={() => setMenuOpen(false)}>{isItalian ? 'Contatti' : 'Contact'}</a><button type="button" onClick={toggleLocale} className="flex items-center gap-2 border-t border-white/20 pt-5 text-left"><Languages size={15} />{isItalian ? 'English' : 'Italiano'}</button></nav>}
      </header>

      <section id="top" className="relative flex min-h-[780px] items-end overflow-hidden bg-ink text-white lg:min-h-screen">
        <div className="pointer-events-none absolute inset-0 overflow-hidden bg-ink" aria-hidden="true">
          <video
            className="absolute left-1/2 top-1/2 h-[56.25vw] min-h-full w-[177.78vh] min-w-full -translate-x-1/2 -translate-y-1/2 scale-[1.08] object-cover"
            src="https://res.cloudinary.com/dcuqtxf8n/video/upload/v1790687382/lonucrnzzfd14oifihpm.mov"
            autoPlay
            muted
            loop
            playsInline
            preload="metadata"
            aria-label="Anvance Elopement cinematic wedding film"
          />
        </div>
        <div className="pointer-events-none absolute inset-0 z-[1] bg-ink/10" aria-hidden="true" />
        <div className="absolute inset-0 bg-gradient-to-t from-ink/85 via-ink/15 to-ink/25" />
        <div className="relative mx-auto w-full max-w-[1440px] px-6 pb-14 pt-36 lg:px-12 lg:pb-20">
          <h1 className="mb-10 flex items-center gap-3 text-[10px] font-normal uppercase tracking-[0.28em] text-white/75"><span className="h-px w-10 bg-white/70" /> {isItalian ? 'Fotografia e videografia per elopement in Italia' : 'Italy Elopement Photography & Videography'}</h1>
          <p className="max-w-4xl font-serif text-[clamp(4rem,11vw,10rem)] leading-[.82] tracking-[-0.055em]">Love,<br /><em className="font-light">unhurried.</em></p>
          <div className="mt-12 flex flex-col justify-between gap-8 border-t border-white/30 pt-5 sm:flex-row sm:items-end"><p className="max-w-sm text-sm leading-6 text-white/80">{isItalian ? 'Elopement intimi in Italia, per coppie che vogliono vivere ogni emozione e ricordarla con sincerità.' : 'Intimate Italian elopements for couples who want to feel everything — and remember it honestly.'}</p><a href="#contact" className="group flex items-center gap-3 text-[11px] uppercase tracking-[0.24em]">{isItalian ? 'Verifica la data' : 'Check our date'} <span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/60 transition-colors group-hover:bg-white group-hover:text-ink"><ArrowDown size={15} /></span></a></div>
        </div>
        <div className="absolute bottom-8 right-8 hidden items-center gap-3 text-[10px] uppercase tracking-[0.22em] text-white/70 lg:flex"><Play size={12} fill="currentColor" /> Sound off · cinematics on</div>
      </section>

      <section id="story" className="mx-auto grid max-w-[1440px] gap-14 px-6 py-28 lg:grid-cols-[.8fr_1.2fr] lg:px-12 lg:py-40">
        <div><p className="eyebrow">A different kind of wedding</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">For the wildly <em>in love.</em></h2></div>
        <div className="grid gap-10 sm:grid-cols-2"><p className="text-lg leading-8 text-ink/75">Anvance is for the couple who would rather chase golden light through olive groves than follow a schedule. We film the quiet, the loud, and every honest in-between.</p><div className="border-t border-ink/20 pt-5 text-sm leading-7 text-ink/65"><p>Based in Italy. Available everywhere your story takes you.</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 border-b border-ink pb-2 text-[11px] uppercase tracking-[.2em] text-ink">Meet your filmmaker <ArrowUpRight size={14} /></a></div></div>
      </section>

      <section className="hidden border-b border-ink/10 bg-[#ece8df] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1180px] gap-10 overflow-hidden rounded-[1.5rem] border border-ink/10 bg-ivory p-6 shadow-[0_24px_80px_rgba(40,32,24,.1)] sm:p-10 lg:grid-cols-[.58fr_1.42fr] lg:items-center lg:gap-16 lg:p-12"><div className="relative mx-auto w-full max-w-[170px] sm:max-w-[200px] lg:max-w-[220px]"><div className="absolute -inset-2 rounded-full border border-terracotta/40" /><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4K6A9265-ba3sSBMLrsmaxXyPA1SaHvb06pLLwJ.jpg" alt="Alessia Zanchi, Italy wedding photographer and planner" className="relative aspect-square w-full rounded-full object-cover object-center" /></div><div><p className="eyebrow">{isItalian ? 'La persona dietro le immagini' : 'The person behind the frames'}</p><h2 className="mt-5 max-w-2xl font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-7xl">{isItalian ? <>Fotografie create da <em>Alessia Zanchi.</em></> : <>Every beautiful frame, by <em>Alessia Zanchi.</em></>}</h2><p className="mt-7 max-w-xl text-lg leading-8 text-ink/70">{isItalian ? 'Per immagini autentiche, un’esperienza senza stress e una pianificazione attenta, Alessia accompagna ogni coppia con cura dall’idea all’ultimo scatto.' : 'The photographs you see here are captured by Alessia Zanchi — a thoughtful photographer and planner who brings calm direction, honest emotion, and an eye for the little moments that make your story yours.'}</p><p className="mt-5 max-w-xl text-sm leading-7 text-ink/60">{isItalian ? 'Se desideri un’esperienza indimenticabile e immagini che ti riportino davvero a quel giorno, contattala per iniziare a progettare qualcosa di straordinario.' : 'If you want more than beautiful photos — if you want an unforgettable experience, a beautifully planned day, and images you will feel for years — Alessia is here to help you make it happen.'}</p><a href="https://alessiazanchi.com/contact-me" target="_blank" rel="noreferrer" className="mt-7 inline-flex w-full items-center justify-center gap-3 rounded-full bg-ink px-5 py-3 text-[10px] uppercase tracking-[.16em] text-ivory transition-all hover:-translate-y-0.5 hover:bg-terracotta hover:shadow-lg sm:w-auto">{isItalian ? 'Contatta Alessia' : 'Plan your experience with Alessia'} <ArrowUpRight size={15} /></a></div></div>      </section>

      <section className="bg-ink px-5 py-20 text-ivory sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1320px]"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow !text-ivory/65">Moving pictures</p><h2 className="mt-4 max-w-2xl font-serif text-5xl leading-[.92] tracking-[-.05em] sm:text-7xl">A different kind<br /><em>of wedding.</em></h2><p className="mt-6 max-w-md text-base leading-7 text-ivory/65">For the wildly in love. Anvance is for couples who would rather chase golden light through olive groves than follow a schedule.</p></div><div className="max-w-sm lg:pb-1"><p className="text-sm leading-7 text-ivory/60">We film the quiet, the loud, and every honest in-between. Based in Italy. Available everywhere your story takes you.</p></div></div><div className="mt-12"><MinimalYouTubePlayer /></div></div></section>

      <section className="border-b border-ink/10 bg-[#ece8df] px-5 py-16 text-ink sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1180px] gap-10 overflow-hidden rounded-[1.5rem] border border-ink/10 bg-ivory p-6 shadow-[0_24px_80px_rgba(40,32,24,.1)] sm:p-10 lg:grid-cols-[.58fr_1.42fr] lg:items-center lg:gap-16 lg:p-12"><div className="grid grid-cols-3 gap-2 sm:gap-3"><div className="mt-8 overflow-hidden rounded-full"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/albert-ykP9jNeFtZ03PfzpNzrmFIaZibELCl.avif" alt="Albert, director and filmmaker at Anvance" className="aspect-[3/4] w-full object-cover" /></div><div className="overflow-hidden rounded-full"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/angelo-xoarnLCN1XkSSkiTIHLLMY0Cxqe7IH.avif" alt="Angelo, creative filmmaker at Anvance" className="aspect-[3/4] w-full object-cover" /></div><div className="mt-8 overflow-hidden rounded-full"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/axel-NzCuzB9dUKx2r1Ku0BF24qVLSID6ti.avif" alt="Axel, creative filmmaker at Anvance" className="aspect-[3/4] w-full object-cover" /></div></div><div><p className="eyebrow">The people behind the films</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-[.96] tracking-[-.04em] sm:text-5xl lg:text-6xl">Every story, shaped by <em>our creative team.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">Albert, Angelo, and Axel bring a shared eye for movement, atmosphere, and the honest moments that make a celebration feel unmistakably yours.</p><p className="mt-4 max-w-xl text-sm leading-7 text-ink/60">From the first idea to the final film, we work quietly and intuitively — giving you space to be present while we turn the in-between into something you will want to return to.</p><a href="/about" className="mt-7 inline-flex w-full items-center justify-center gap-3 rounded-full bg-ink px-5 py-3 text-[10px] uppercase tracking-[.16em] text-ivory transition-all hover:-translate-y-0.5 hover:bg-terracotta sm:w-auto">Meet the creative team <ArrowUpRight size={14} /></a></div></div></section>

      <section id="places" className="bg-[#f4f0e9] px-5 py-20 text-ink sm:px-8 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1320px]"><div className="grid gap-8 border-b border-ink/15 pb-12 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow text-ink/55">Where we wander</p><h2 className="mt-4 max-w-3xl font-serif text-5xl leading-[.9] tracking-[-.05em] sm:text-7xl lg:text-8xl">Italy, in all<br /><em>her moods.</em></h2></div><div className="max-w-sm lg:pb-1"><p className="text-sm leading-7 text-ink/65">From quiet lake mornings to salt-air coastlines, choose the place that feels like the beginning of your story.</p><a href="/portfolio" className="mt-5 inline-flex items-center gap-2 border-b border-ink/40 pb-2 text-[10px] uppercase tracking-[.2em] transition-colors hover:border-ink">Explore every album <ArrowUpRight size={14} /></a></div></div><FeaturedAlbums /></div></section>

      <section className="border-b border-ink/10 bg-[#ece8df] px-5 py-16 text-ink sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto grid max-w-[1180px] gap-10 overflow-hidden rounded-[1.5rem] border border-ink/10 bg-ivory p-6 shadow-[0_24px_80px_rgba(40,32,24,.1)] sm:p-10 lg:grid-cols-[.58fr_1.42fr] lg:items-center lg:gap-16 lg:p-12"><div className="relative mx-auto w-full max-w-[170px] sm:max-w-[200px] lg:max-w-[220px]"><div className="absolute -inset-2 rounded-full border border-terracotta/40" /><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/4K6A9265-ba3sSBMLrsmaxXyPA1SaHvb06pLLwJ.jpg" alt="Alessia Zanchi, Italy wedding photographer and planner" className="relative aspect-square w-full rounded-full object-cover object-center" /></div><div><p className="eyebrow">The person behind the frames</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-[.96] tracking-[-.04em] sm:text-5xl lg:text-6xl">Every beautiful frame, by <em>Alessia Zanchi.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">Thoughtful photography, calm direction, and honest images for couples who want their Italy elopement to feel completely their own.</p><a href="https://alessiazanchi.com/contact-me" target="_blank" rel="noreferrer" className="mt-7 inline-flex w-full items-center justify-center gap-3 rounded-full bg-ink px-5 py-3 text-[10px] uppercase tracking-[.16em] text-ivory transition-all hover:-translate-y-0.5 hover:bg-terracotta sm:w-auto">Plan your experience with Alessia <ArrowUpRight size={14} /></a></div></div></section>

      <section id="investment" className="mx-auto max-w-[1440px] px-6 py-28 lg:px-12 lg:py-40"><div className="flex flex-col justify-between gap-8 border-b border-ink/20 pb-12 md:flex-row md:items-end"><div><p className="eyebrow">Investment</p><h2 className="mt-5 max-w-xl font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-7xl">A day that feels<br /><em>like yours.</em></h2></div><div className="max-w-xs"><p className="text-sm leading-6 text-ink/65">Every collection includes thoughtful planning, a calm presence, and photographs and films made to return to forever.</p><a href="/anvance-investment-guide.txt" download className="mt-6 inline-flex items-center gap-2 border-b border-ink pb-2 text-[11px] uppercase tracking-[.2em]">Download investment guide <ArrowUpRight size={14} /></a></div></div><div className="mx-auto mt-10 grid max-w-5xl gap-4 lg:grid-cols-2">{packages.map((pkg) => <article key={pkg.name} className={`relative flex flex-col border p-7 ${pkg.featured ? 'border-terracotta bg-terracotta text-ivory lg:-mt-5 lg:mb-5' : 'border-ink/20'}`}><div className="flex items-start justify-between"><p className="font-serif text-3xl">{pkg.name}</p>{pkg.featured && <span className="text-[9px] uppercase tracking-[.18em]">Most loved</span>}</div><p className={`mt-6 text-4xl font-light ${pkg.featured ? 'text-ivory' : ''}`}>{pkg.price}</p><p className={`mt-3 min-h-12 text-sm leading-6 ${pkg.featured ? 'text-ivory/75' : 'text-ink/60'}`}>{pkg.note}</p><ul className={`mt-8 space-y-3 border-t pt-6 text-sm ${pkg.featured ? 'border-ivory/30' : 'border-ink/15'}`}>{pkg.features.map((feature) => <li key={feature} className="flex gap-3"><Check size={15} className="mt-0.5 shrink-0" />{feature}</li>)}</ul><a href="#contact" className={`mt-10 inline-flex items-center justify-between border-t pt-4 text-[11px] uppercase tracking-[.2em] ${pkg.featured ? 'border-ivory/30' : 'border-ink/20'}`}>Check our date <ArrowUpRight size={15} /></a></article>)}</div></section>

      <section id="contact" className="bg-sand px-6 py-24 lg:px-12 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Start here</p><h2 className="mt-5 font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-7xl">Tell us<br /><em>everything.</em></h2><p className="mt-8 max-w-sm text-sm leading-6 text-ink/65">Dates, daydreams, the little things that matter to you. We read every note personally and reply within 48 hours. This is a preview enquiry form for now.</p><div className="mt-8 border-l-2 border-terracotta pl-4 text-sm leading-6"><p className="font-serif text-xl">Now booking 2027</p><p className="mt-1 text-ink/60">Tell us your preferred date and a second option so we can guide you quickly.</p></div></div><form className="grid gap-6" onSubmit={async (e) => { e.preventDefault(); const form = e.currentTarget; const response = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); if (response.ok) setSubmitted(true) }}>{submitted ? <div className="flex min-h-72 flex-col justify-center border-t border-ink/20"><p className="eyebrow">Thank you</p><p className="mt-4 font-serif text-4xl">Your story is on its way.</p><p className="mt-4 text-sm text-ink/65">We will be in touch within 48 hours.</p></div> : <><div className="grid gap-6 sm:grid-cols-2"><label className="field">Your names<input required name="name" placeholder="Elena & Marco" /></label><label className="field">Email address<input required type="email" name="email" placeholder="hello@example.com" /></label><label className="field">Phone number<input type="tel" name="phone" placeholder="+39 333 123 4567" autoComplete="tel" /></label></div><div className="grid gap-6 sm:grid-cols-2"><label className="field">Preferred date<input required type="date" name="date" /></label><label className="field">Second date option<input type="date" name="alternateDate" /></label></div><div className="grid gap-6 sm:grid-cols-2"><label className="field">Destination<input required name="place" placeholder="Tuscany, Como, Amalfi..." /></label><label className="field">What are you looking for?<select name="service" defaultValue="Photography & film"><option>Photography & film</option><option>Photography</option><option>Film</option></select></label></div><label className="field">A little about you<textarea required name="message" rows={4} placeholder="Tell us what you are imagining..." /></label><button className="mt-2 flex w-full items-center justify-between bg-ink px-6 py-5 text-left text-[11px] uppercase tracking-[.22em] text-ivory transition-colors hover:bg-terracotta">Check our date <ArrowUpRight size={16} /></button></>}</form></div></section>
      <section className="border-y border-ink/10 bg-[#ece8df] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Italy wedding films & photography</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-[.94] tracking-[-.04em] sm:text-6xl">Your place.<br /><em>Your pace.</em></h2></div><div className="grid gap-6 text-sm leading-7 text-ink/70 sm:grid-cols-2"><p>Planning a Tuscany elopement, a Lake Como wedding, or an intimate celebration on the Amalfi Coast? Anvance creates cinematic wedding films and documentary photography for destination weddings across Italy.</p><p>We also travel to the Dolomites, Venice, Puglia and Sicily for couples who want an intentional, artful record of the day. Enquire now to reserve a 2027 date and receive calm planning guidance from the first idea to the final film.</p></div></div></section>

      <section id="faq" className="mx-auto max-w-[1440px] px-6 py-24 lg:px-12 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Good to know</p><h2 className="mt-5 font-serif text-5xl leading-[.94]">Before we<br /><em>begin.</em></h2></div><div className="divide-y divide-ink/15 border-y border-ink/15">{[['How far in advance should we book?', 'Most couples enquire 6–18 months ahead. We sometimes have last-minute availability, so it is always worth asking.'], ['What is included in travel?', 'Travel fees across Italy are included. For destinations outside Italy, we will create a clear custom quote before booking.'], ['When will we receive our film?', 'Your teaser arrives within 1 week, and your finished films are delivered through a private download link within 4 weeks of your elopement.'], ['Do you offer both photography and film?', 'Yes. Anvance combines documentary photography with cinematic wedding films, preserving the quiet details, movement, sound, and feeling of your day in one cohesive visual story.']].map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between font-serif text-2xl">{question}<span className="text-2xl transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl text-sm leading-7 text-ink/65">{answer}</p></details>)}</div></div></section>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'LocalBusiness', name: 'Anvance Elopement', description: 'Wedding photography and cinematic elopement films across Italy.', url: 'https://www.anvanceelopement.com', areaServed: ['Italy', 'Amalfi Coast', 'Tuscany', 'Lake Como', 'Dolomites'], priceRange: '€€' }) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'VideoObject', name: 'Anvance Elopement — Italian elopement film', description: 'Cinematic elopement videography and photography across Italy.', thumbnailUrl: 'https://res.cloudinary.com/dcuqtxf8n/video/upload/so_0,w_1600,q_auto/lonucrnzzfd14oifihpm.jpg', contentUrl: 'https://res.cloudinary.com/dcuqtxf8n/video/upload/v1790687382/lonucrnzzfd14oifihpm.mov', uploadDate: '2026-01-01', publisher: { '@type': 'Organization', name: 'Anvance Elopement' } }) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'Review', itemReviewed: { '@type': 'LocalBusiness', name: 'Anvance Elopement' }, author: { '@type': 'Person', name: 'Lyndsey DeRamus' }, reviewRating: { '@type': 'Rating', ratingValue: '5', bestRating: '5' }, reviewBody: testimonials[0].quote }) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [['How far in advance should we book?', 'Most couples enquire 6–18 months ahead.'], ['When will we receive our film?', 'Your teaser arrives within 1 week, and your finished films are delivered through a private download link within 4 weeks.']].map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) }) }} />
      <footer className="bg-ink px-6 py-14 text-ivory lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 border-b border-ivory/15 pb-12 md:grid-cols-[1.2fr_.8fr_.8fr] md:gap-8"><div><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/anvanceelopmentlogo-aXDhassIf5mIXnPRdFpEdZ8EBnS1az.png" alt="Anvance Elopement" className="w-[190px] max-w-full object-contain" /><p className="mt-4 max-w-xs text-sm leading-6 text-ivory/55">Italy elopement photography, cinematic wedding films, and thoughtful planning for couples who want their day to feel entirely their own.</p></div><nav aria-label="Footer navigation"><p className="text-[10px] uppercase tracking-[.2em] text-ivory/40">Explore</p><div className="mt-4 grid gap-3 text-sm text-ivory/70"><a href="#top" className="transition-colors hover:text-ivory">Home</a><a href="/portfolio" className="transition-colors hover:text-ivory">Portfolio</a><a href="/about" className="transition-colors hover:text-ivory">About</a><a href="/contact" className="transition-colors hover:text-ivory">Contact</a></div></nav><div><p className="text-[10px] uppercase tracking-[.2em] text-ivory/40">Follow & enquire</p><div className="mt-4 grid gap-3 text-sm text-ivory/70"><a href="tel:+393407421347" className="transition-colors hover:text-ivory">+39 340 742 1347</a><a href="https://instagram.com/anvance.elopement" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 transition-colors hover:text-ivory"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/instagram/mono.svg" alt="" className="h-4 w-4 invert" /> Instagram</a><a href="https://www.tiktok.com/@anvance.elopement" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 transition-colors hover:text-ivory"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/tiktok/mono.svg" alt="" className="h-4 w-4 invert" /> TikTok</a><a href="/contact" className="mt-2 inline-flex w-fit rounded-full border border-ivory/35 px-4 py-2 text-[10px] uppercase tracking-[.16em] transition-colors hover:border-ivory hover:bg-ivory hover:text-ink">Check your date</a></div></div></div><div className="flex flex-col gap-3 pt-6 text-[10px] uppercase tracking-[.16em] text-ivory/35 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Anvance Elopement · Italy</span><span>Photography · Videography · Elopement Planning</span></div></div></footer>
    </main>
  )
}

function PlaceCard({ image, name, sub }: { image: string; name: string; sub: string }) { return <a href="#contact" className="group relative aspect-[.82] overflow-hidden bg-ink"><img src={image} alt={`${name} elopement location in Italy`} className="h-full w-full object-cover opacity-80 transition duration-700 group-hover:scale-105 group-hover:opacity-95" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-ink/80 to-transparent p-6 pt-20"><p className="font-serif text-3xl">{name}</p><p className="mt-1 text-[10px] uppercase tracking-[.16em] text-ivory/70">{sub}</p></div></a> }

function unused() { return null }

